config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'lists#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
    get :following, :followers
    end
  end 
  # Review: Can we use lists/new & tasks/new pages here?
  get  '/list/new',  to: 'lists#new'
  get  '/lists/:id',  to: 'lists#show'
  # Review: Nest tasks/new under lists
  get  '/task/:id',  to: 'tasks#new'

  # Review: Can we limit the allowed actions for ALL routes?
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :lists,                 only: [:new, :create, :destroy, :edit]
  # Review: Can we nest tasks, list_share, taskusers inside lists
  # Review: Can we use underscored names for listusers, taskusers i.e changing them to list_users and taks_users 
  resources :tasks,          only: [:create, :destroy]
  resources :listusers,        only: [:create, :destroy]
  # Review: Can we nest taskusers inside tasks
  resources :taskusers,        only: [:create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :listusers, dependent: :destroy
  has_many :users, through: :listusers
  has_many :taskusers, dependent: :destroy
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :load_list, only: [:show]

  def home
    @collaborators = User.all_except(current_user).collect {|p| [ p.email, p.id ] }
    @user_lists = current_user.lists
    @collaborated_lists = current_user.collaborated_lists
    @assigned_tasks = current_user.assigned_tasks
  end

  def create
    @list = current_user.lists.new(list_params) 
    if @list.save
      flash[:success] = "List created!"
      redirect_to action: 'show', id: @list.id
    else
      flash[:danger] = @list.errors.full_messages.to_sentence
      redirect_to root_url
    end
  end

  def show
    @tasks = @list.tasks
    @collaborated_users = @list.users.collect {|p| [ p.email, p.id ] }
  end

  private

  def list_params
    params.require(:list).permit(:name, :content)
  end

  def load_list
    @list = current_user.all_lists.where(id: params[:id]).first
    return redirect_to root_url if @list.nil?
  end
end

app/helpers/lists_helper.rb
module ListsHelper
    def options_for_seasons
        ['Spring', 'Summer', 'Autumn', 'Winter']
    end
end

app/views/lists/home.html.erb
<% provide(:title, 'Create Task') %>
<h1>My List</h1>
<!-- Trigger the modal with a button -->
<a href="/list/new">
    <button type="button" class="btn btn-info btn-lg" >Add List</button>
</a>
<% if @user_lists.any? %>
  <table class="table">
    <thead>
      <tr> 
        <th>Name</th>
        <th>Content</th>
        <th>Share List</th>
        <th>Shared User</th>
      </tr>
    </thead>
    <tbody>
      <% @user_lists.each do |list| %><tr>
          <td> <%= link_to list.name, list  %></td>
          <td><%= list.content  %></td>
          <td>
            <button type="button" class="btn btn-info btn-lg share" data-id = "<%= list.id %>" data-toggle="modal" data-target="#myModal">Share</button>
          </td>
          <td>
            <% if list.users.any? %>
              <% list.users.each do |user| %>
                <%= user.email %>
                <% list.listusers.each do |list_user| %>
                  <% if user.id == list_user.user_id %>
                    <%=  link_to "Delete user", listuser_path( list_user.id ), remote: true, method: :delete %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>    
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<h1>Assigned List</h1>
<% if @collaborated_lists.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Content</th>
      </tr>
    </thead>
    <tbody>
    <% @collaborated_lists.each do |list| %><tr>
        <td> <%= list.name  %></td>
        <td><%= list.content  %></td>
      </tr>
    <% end %> 
    </tbody>
  </table>
<% end %>
<h1>Assigned Task</h1>
<% if @assigned_tasks.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Content</th>
      </tr>
    </thead>
    <tbody>
      <% @assigned_tasks.each do |task| %>
        <tr>
          <td> <%= task.name  %></td>
          <td><%= task.content  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Share List</h4>
      </div>
      <div class="modal-body">
        <%= form_for :listuser, :url => {:controller => 'listusers', :action => "create" } do |f| %>
          <%= f.hidden_field :list_id %>
          <%= f.label :select %>
          <%= f.select :user_id, @collaborators, { include_blank: 'Select User' } %>      
          <%= f.submit "Share User", class: "btn btn-primary" %>
        <% end %>        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<% provide(:title, 'Create Task') %>
<h1>Create List</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :list, :url => {:controller => 'lists', :action => "create" } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.text_area :content, placeholder: "content..." %>
      <%= f.submit "Create new list", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb

<% provide(:title, 'Task List') %>
<h1>Task List</h1>
<a href="/task/<%= params[:id] %>">
  <button type="button" class="btn btn-info btn-lg" >Add Task</button>
</a>
<% if @tasks.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Content</th>
        <th>Assign Task</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %><tr>
          <td> <%=  task.name  %></td>
          <td><%= task.content  %></td>
          <td>
            <button type="button" class="btn btn-info btn-lg assign" data-id = "<%= task.id %>" data-toggle="modal" data-target="#myModal">Assign</button>
          </td>
        </tr>
      <% end %>      
    </tbody>
  </table>
<% end %>
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Assign Task</h4>
      </div>
      <div class="modal-body">
        <%= form_for :taskusers, :url => {:controller => 'taskusers', :action => "create" } do |f| %>
          <%= f.hidden_field :task_id %>          
          <%= f.hidden_field :list_id, value: @list.id %> 
          <%= f.label :select %>
          <%= f.select :user_id, @collaborated_users, { include_blank: 'Select User' } %>      
          <%= f.submit "Assign Task", class: "btn btn-primary" %>
        <% end %>        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>